### ISSUE TITLE
Configure Pymato to use User sounds.

### ISSUE THREAD

**Issue by Areahints** [waynew/pymato#1]
Would it be possible to tell pymato what sounds to use?
```
pymato pom doing something -s /path to secs.mp3   -r /path to complete.mp3
```
- -s = tell the program to use a file as the seconds' timer or countdown timer. It really brings the focus in.

- -r =when a pom is resolved or completed, play this sound.

With my current config, I get a 2secs vibration when a pom is completed, which is very easy to miss.

**Comment by waynew** [comment]
When you say `as the seconds' timer or countdown timer`, do you mean that it would be executed once for every second? That's an interesting thought.

For the latter, I think I would just recommend using the natural shell functionality. For fish shell it would be:

```
pymato pom doing something; <play command> path/to/complete.mp3
```

That might also work in `bash`, or perhaps `&&` is needed. For the completion command I would totally merge a PR that added that to the README.
