### ISSUE TITLE
Make Task Time in Pymato Log Human Readable

### ISSUE THREAD

**Issue by Areahints** [waynew/pymato#2]
After running a pymato track session, the log outputs:

`2019-08-31 08:21:32+0000 2019-08-31 09:15:45+0000 Updating Trello`

I have to subtract time from both markers to get an idea of how much time is spent.

is it possible for the log to record this?

`2019-08-31 08:21:32+0000 2019-08-31 09:15:45+0000 - total time spent 0:54:11 - Updating Trello`

**Comment by waynew** [comment]
Are you using `pymato log`?

**Comment by waynew** [comment]
```
~> pymato log
2018-10-27
         1h   29s review shaanxi

2019-08-31
               2s things
              11s things
------------------------------
         1h   42s total pomodoro time
```
That's what I get

**Comment by Areahints** [comment]
Ah yes, I got this when I typed `pymato log` in my terminal.

I was accessing the log file directly. this is a better alternative. 

Cheers.
